import type { CareNeed, Facility, UserProfile } from "./types";

export const defaultProfile: UserProfile = {
  name: "Ananya Sharma",
  dateOfBirth: "1984-04-18",
  location: "Jaipur, Rajasthan",
  currentProblems: "Stage 4 CKD; intermittent fatigue",
  medicalHistory: "Hypertension, diabetes, no known drug allergies",
  insuranceNumber: "INS-DEMO-2049",
  governmentHealthCard: "ABHA-DEMO-7781",
  budgetType: "Balanced",
  travelTime: "Quickest",
  preferredTransportation: "Cab",
  role: "patient",
};

export const careNeeds: CareNeed[] = [
  "Dialysis",
  "Trauma",
  "Cardiology",
  "Maternity",
  "Oncology",
  "General medicine",
];

export const facilities: Facility[] = [
  {
    id: "jaipur-renal-access",
    name: "Prism Demo Renal Access Center",
    facilityType: "Specialty clinic",
    region: "Jaipur North",
    city: "Jaipur",
    distanceKm: 4.8,
    services: ["Dialysis", "General medicine"],
    priceIndex: 2,
    averageVisitCost: 3200,
    waitMinutes: 55,
    evidenceConfidence: 86,
    availability: "Dialysis slots reported for morning and evening shifts",
    phone: "+91 141 000 0142",
    booking: "Call front desk; referral note preferred for first visit",
    evidence: [
      {
        label: "Dialysis service listed in facility registry",
        source: "Demo facility registry",
        freshness: "Snapshot 2026-06-15",
        confidence: 92,
      },
      {
        label: "Nephrology capability found in extracted facility brochure",
        source: "Indexed facility notes",
        freshness: "Indexed 2026-06-12",
        confidence: 84,
      },
    ],
    missingEvidence: ["Same-day slot confirmation", "Out-of-pocket package price"],
    suspiciousSignals: [],
    travelTimes: {
      Ambulance: 16,
      Cab: 22,
      Train: null,
      "Own vehicle": 20,
    },
    hotels: [
      { name: "Hotel Lattice Jaipur", distanceKm: 0.8, tier: "Balanced", nightlyEstimate: 4100 },
      { name: "North Gate Stay", distanceKm: 1.5, tier: "Economy", nightlyEstimate: 2100 },
      { name: "Aster Club Suites", distanceKm: 2.2, tier: "Luxury", nightlyEstimate: 8800 },
    ],
  },
  {
    id: "pinkcity-trauma-hub",
    name: "Prism Demo Pink City Trauma Hub",
    facilityType: "Emergency hospital",
    region: "Jaipur Central",
    city: "Jaipur",
    distanceKm: 6.2,
    services: ["Trauma", "Cardiology", "General medicine"],
    priceIndex: 3,
    averageVisitCost: 7600,
    waitMinutes: 18,
    evidenceConfidence: 82,
    availability: "24/7 emergency intake; operating theatre status must be confirmed",
    phone: "+91 141 000 0198",
    booking: "Emergency desk accepts direct arrival; call before non-emergency referral",
    evidence: [
      {
        label: "Emergency and trauma intake marked available",
        source: "Demo emergency capability",
        freshness: "Snapshot 2026-06-15",
        confidence: 88,
      },
      {
        label: "Ambulance bay and imaging services detected in ops feed",
        source: "Demo operations signals",
        freshness: "Updated hourly demo feed",
        confidence: 79,
      },
    ],
    missingEvidence: ["Current ICU bed count", "Specialist on-call roster"],
    suspiciousSignals: ["Pricing differs by more than 30% across two stale extracts"],
    travelTimes: {
      Ambulance: 14,
      Cab: 26,
      Train: null,
      "Own vehicle": 24,
    },
    hotels: [
      { name: "Central Care Inn", distanceKm: 0.5, tier: "Balanced", nightlyEstimate: 4500 },
      { name: "Cityline Rooms", distanceKm: 1.7, tier: "Economy", nightlyEstimate: 2400 },
      { name: "The Meridian Jaipur", distanceKm: 1.1, tier: "Elite", nightlyEstimate: 15200 },
    ],
  },
  {
    id: "aravalli-multicare",
    name: "Prism Demo Aravalli Multicare",
    facilityType: "Multispecialty hospital",
    region: "Jaipur West",
    city: "Jaipur",
    distanceKm: 8.9,
    services: ["Dialysis", "Trauma", "Cardiology", "Maternity", "General medicine"],
    priceIndex: 3,
    averageVisitCost: 6400,
    waitMinutes: 35,
    evidenceConfidence: 91,
    availability: "Broad specialty coverage; appointment desk open until 8 PM",
    phone: "+91 141 000 0156",
    booking: "Online request plus phone confirmation",
    evidence: [
      {
        label: "Multiple services verified across registry and brochure",
        source: "Demo care service map",
        freshness: "Snapshot 2026-06-15",
        confidence: 93,
      },
      {
        label: "Recent referral completions logged for nephrology and emergency",
        source: "Demo referral history",
        freshness: "Last 30 days",
        confidence: 90,
      },
    ],
    missingEvidence: ["Procedure-level price sheet"],
    suspiciousSignals: [],
    travelTimes: {
      Ambulance: 21,
      Cab: 34,
      Train: 48,
      "Own vehicle": 32,
    },
    hotels: [
      { name: "Westline Suites", distanceKm: 0.6, tier: "Luxury", nightlyEstimate: 9400 },
      { name: "Pratap Budget Lodge", distanceKm: 2.1, tier: "Economy", nightlyEstimate: 1900 },
      { name: "Aravalli Residency", distanceKm: 1.2, tier: "Balanced", nightlyEstimate: 5200 },
    ],
  },
  {
    id: "sanganer-community-care",
    name: "Prism Demo Sanganer Community Care",
    facilityType: "Public hospital",
    region: "Jaipur South",
    city: "Jaipur",
    distanceKm: 11.4,
    services: ["General medicine", "Maternity", "Dialysis"],
    priceIndex: 1,
    averageVisitCost: 900,
    waitMinutes: 95,
    evidenceConfidence: 74,
    availability: "Economy option; dialysis availability appears limited",
    phone: "+91 141 000 0120",
    booking: "Walk-in queue; carry government health card",
    evidence: [
      {
        label: "Public hospital listing includes renal support",
        source: "Demo public registry",
        freshness: "Snapshot 2026-05-28",
        confidence: 76,
      },
      {
        label: "Lower pricing signal from reimbursement claims",
        source: "Demo price ranges",
        freshness: "Last quarter",
        confidence: 71,
      },
    ],
    missingEvidence: ["Dialysis chair count", "Queue length by day", "Live phone confirmation"],
    suspiciousSignals: ["One source lists dialysis as referral-only"],
    travelTimes: {
      Ambulance: 29,
      Cab: 42,
      Train: 58,
      "Own vehicle": 38,
    },
    hotels: [
      { name: "Sanganer Guest House", distanceKm: 1.4, tier: "Economy", nightlyEstimate: 1500 },
      { name: "Airport Road Stay", distanceKm: 2.8, tier: "Balanced", nightlyEstimate: 3600 },
      { name: "South Jaipur Grand", distanceKm: 4.2, tier: "Luxury", nightlyEstimate: 7900 },
    ],
  },
  {
    id: "malviya-oncology-cardiac",
    name: "Prism Demo Malviya Specialty Institute",
    facilityType: "Specialty hospital",
    region: "Jaipur East",
    city: "Jaipur",
    distanceKm: 12.7,
    services: ["Oncology", "Cardiology", "General medicine"],
    priceIndex: 4,
    averageVisitCost: 11800,
    waitMinutes: 40,
    evidenceConfidence: 88,
    availability: "Specialist appointments usually require prior booking",
    phone: "+91 141 000 0184",
    booking: "Online intake; coordinator callback recommended",
    evidence: [
      {
        label: "Oncology and cardiology service taxonomy match",
        source: "Demo facility registry",
        freshness: "Snapshot 2026-06-15",
        confidence: 91,
      },
      {
        label: "Published referral documents mention tumor board review",
        source: "Indexed facility notes",
        freshness: "Indexed 2026-06-08",
        confidence: 85,
      },
    ],
    missingEvidence: ["Current appointment lead time", "Insurance network status"],
    suspiciousSignals: [],
    travelTimes: {
      Ambulance: 27,
      Cab: 46,
      Train: 62,
      "Own vehicle": 41,
    },
    hotels: [
      { name: "Malviya Comforts", distanceKm: 1.0, tier: "Balanced", nightlyEstimate: 4800 },
      { name: "Pearl Business Hotel", distanceKm: 0.9, tier: "Luxury", nightlyEstimate: 9300 },
      { name: "East Jaipur Hostel", distanceKm: 3.1, tier: "Economy", nightlyEstimate: 1700 },
    ],
  },
  {
    id: "civil-lines-mother-child",
    name: "Prism Demo Civil Lines Mother and Child",
    facilityType: "Women and child hospital",
    region: "Jaipur Central",
    city: "Jaipur",
    distanceKm: 7.1,
    services: ["Maternity", "General medicine"],
    priceIndex: 2,
    averageVisitCost: 5200,
    waitMinutes: 45,
    evidenceConfidence: 80,
    availability: "Maternity intake and routine antenatal appointments",
    phone: "+91 141 000 0167",
    booking: "Call appointment desk; emergency triage available",
    evidence: [
      {
        label: "Maternity service present in registry",
        source: "Demo facility registry",
        freshness: "Snapshot 2026-06-15",
        confidence: 83,
      },
      {
        label: "Patient guidance documents list antenatal package",
        source: "Indexed facility notes",
        freshness: "Indexed 2026-06-10",
        confidence: 77,
      },
    ],
    missingEvidence: ["NICU bed availability", "Package price by room type"],
    suspiciousSignals: [],
    travelTimes: {
      Ambulance: 19,
      Cab: 30,
      Train: null,
      "Own vehicle": 28,
    },
    hotels: [
      { name: "Civil Lines Studio Stay", distanceKm: 0.7, tier: "Balanced", nightlyEstimate: 3900 },
      { name: "Pink Square Rooms", distanceKm: 2.6, tier: "Economy", nightlyEstimate: 2200 },
      { name: "Rajmahal Suites", distanceKm: 1.5, tier: "Elite", nightlyEstimate: 16800 },
    ],
  },
];

export const analyticsSnapshot = {
  generatedAt: "2026-06-15 18:30 IST",
  source: "Prism healthcare analytics snapshot",
  facilityCount: 124,
  regionsCovered: 7,
  evidenceConfidence: 82,
  missingPriceFields: 31,
  referralCompletionRate: 68,
};
